# nixpacks.toml - Configuração para Railway com suporte ao Puppeteer

[phases.setup]
nixPkgs = [
  "chromium",
  "nodejs-18_x"
]

aptPkgs = [
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libasound2"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build concluído'"]

[start]
cmd = "npm start"

[variables]
USE_REAL_SCRAPING = "false"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
