# nixpacks.toml - Configuração para Railway com Puppeteer

[phases.setup]
# Instalar Chromium via nixpkgs
nixPkgs = [
  "chromium",
  "nodejs-18_x"
]

[phases.install]
# Instalar dependências do Node
cmds = ["npm install --omit=dev"]

[phases.build]
# Build concluído
cmds = ["echo 'Build complete'"]

[start]
# Iniciar servidor
cmd = "npm start"

[variables]
# Variáveis de ambiente
USE_REAL_SCRAPING = "false"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
